services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules